name: Changelog Linter

on:
  pull_request:

jobs:
  lint-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Run changelog linter
      uses: MalteHerrmann/changelog-lint-action@v0.2.1
