name: Cargo Build & Test

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: build & test changelog utils
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # NOTE: instructions copied from: https://nexte.st/docs/installation/pre-built-binaries/#linux-x86_64
      - run: curl -LsSf https://get.nexte.st/0.9.105/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      # Setup rust
      - uses: dtolnay/rust-toolchain@stable

      # Build
      - run: cargo build --verbose --locked

      # Run tests
      - run: cargo nextest run --verbose --features remote --profile CI
        env:
          CARGO_TERM_COLOR: always
